version: '3.8'

services:
  mga-bot:
    build: .
    container_name: mga-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./project_counter.json:/app/project_counter.json
      - ./logs:/app/logs
      - ./service-account-key.json:/app/service-account-key.json:ro
    ports:
      - "8443:8443"
    networks:
      - mga-network

networks:
  mga-network:
    name: mga-network
    driver: bridge